### ISSUE TITLE
Setup a private Monitoring infrastructure

### ISSUE THREAD

**Issue by clone1018** [minotar/imgd#140]
We need to be able to closely monitor all of our servers and how their performing to watch for stability issues and bad code changes.

**Comment by LukeHandle** [comment]
Utilizing the Master server, the current plan is for something like collectd and statsd (may use the collectd plugin) and feed that into Graphite(/Grafana).

From imgd we'll probably use statsd protocol and then collectd will monitor Redis, Varnish and the servers.

This should make nice pretty graphs and stuff allowing us to do do #141

**Comment by lenovouser** [comment]
You might want to take a look at [prometheus.io](http://prometheus.io/). [freegeoip](https://github.com/fiorix/freegeoip) uses it and both is based on Go too. [freegeoip/apiserver](https://github.com/fiorix/freegeoip/tree/master/apiserver) is where they implemented it. [Here](https://github.com/fiorix/freegeoip/issues/150) is some explanation + there are some screenshots from the developer.

**Comment by LukeHandle** [comment]
Hey @lenovouser, I'm sure you are long past caring - but we went ahead with Prometheus. Thanks for the suggestion!m :smile:

It'd be nice to open up the metrics somehow, but maybe on a status page we could show a subset instead.
