### ISSUE TITLE
"char" is a valid username

### ISSUE THREAD

**Issue by jomo** [minotar/imgd#149]
This guy named "baumans" changed their name to "Char": https://api.mojang.com/user/profiles/f2e9994f94934e08974e2f4b7f7843ea/names

That makes char a valid username. They also have a valid skin: http://skins.minecraft.net/MinecraftSkins/Char.png

~~You might want to change the default skin name to "Steve", that's not taken and I guess Mojang prevents people from using that name.~~

This is going to be a breaking change and I'm not sure how you can solve it properly.

----

You could, of course, keep it as it is, but then the user char would never see their avatar.

**Comment by jomo** [comment]
Seems like [not many](https://www.google.com/search?q="minotar.net/avatar/char"&start=20) things are using the "char" hardcoded.

**Comment by LukeHandle** [comment]
What a pain. I'm inclined to change the hardcoded name to "Steve" as you say because it more accurately reflects the Steve vs. Alex characters, but then again, a single user who has a Steve skin vs. a few websites which are still relying char.

I think if we can be sure that Steve is unobtainable by players as a name it makes more sense to begin a transition to it and possibly in X months we can remove the char override.

**Comment by jomo** [comment]
[yes. I mean no](https://bugs.mojang.com/browse/MC-78198)

**Comment by LukeHandle** [comment]
The solution being then "MHF_Steve" as the username which we can safely guarantee is and will stay correct. Still feel sad about getting rid of char...

**Comment by jomo** [comment]
Yep. That's what we will do at Crafatar, too (https://github.com/crafatar/crafatar/issues/142).
Also note there is a slight difference between the original '[char](https://minecraft.net/images/char.png)' and the '[steve](https://minecraft.net/images/steve.png)' avatar (char has a stronger beard).

**Comment by LukeHandle** [comment]
We switched to the new one (without beard) back here https://github.com/minotar/minecraft/pull/2 And yeah, I think I'll add some tracking for char, I can't see us ever fully deprecating it though. I'm expecting the majority of requests are for Steve by a long way and not for the legacy user.
