### ISSUE TITLE
SSL Certificate Error .. again

### ISSUE THREAD

**Issue by davisable** [minotar/imgd#160]
Chrome (and likely other browsers) is showing an SSL error for Minotar preventing any avatar images from loading for the past 48 hours or so:

```This server could not prove that it is minotar.net; its security certificate expired 67 day(s) ago. ```

The SSL expiration was fixed/renewed in #148 so this is likely a configuration issue with the server/SSL setup.

**Comment by LukeHandle** [comment]
That was fixed by switching back to CloudFlare, I understand from clone1018 there was a lsight redirect error somewhere and this should be fixed very soon(TM)

**Comment by clone1018** [comment]
Fixed

**Comment by davisable** [comment]
Great thanks for the quick response guys.
