### ISSUE TITLE
Wrong avatar for KillerN10

### ISSUE THREAD

**Issue by jomo** [minotar/imgd#161]
Crafatar:
![crafatar](https://crafatar.com/avatars/KillerN10?helm&size=160)

Lapis Blue:
![lapis blue](https://lapitar.lapis.blue/helm/160/KillerN10)

Minotar:
![minotar](https://minotar.net/helm/KillerN10/160)

Actual skin:
![skin](http://textures.minecraft.net/texture/de78692fef3fabc9c99753d794c9a53e366dc46e2f6ad35d52ff42a2f5a43df4)

-----

Maybe that user recently changed the avatar and it's just cached?

**Comment by LukeHandle** [comment]
I assume cached, on a local imgd instance it loads the current.

**Comment by MisterFixx** [comment]
is /refresh still exists? if yes you can just call that URL and it'll delete the cache.

**Comment by clone1018** [comment]
No it does not, too many servers to delete cache from.
