### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by FoxInFlame** [minotar/imgd#163]
Having a Minecraft head for the favicon would be really good.
When going to other tabs, to for example check your mail, you can look at the favicon for Minotar, and realise, "Oh, that Minotar site is about Steve!".
It is possible to dynamically change Favicons using Javascript, so I am looking forward for it!

**Comment by jomo** [comment]
There is a favicon (?)
![screenshot](https://i.imgur.com/oUXesA8.png)

**Comment by FoxInFlame** [comment]
I mean a different favicon for each Player.
For example, if you go to http://minotar.net/blah/Steve, then the favicon should change to Steve's head.

**Comment by jomo** [comment]
You can only set a favicon for HTML content, not for images.
However, at least Firefox uses the image as favicon:
![screenshot](https://i.imgur.com/XPD4BpT.png)

**Comment by FoxInFlame** [comment]
Thank you for the information. I did not know about this, and I thought it was a normal HTML website. Now I know. Minotar has no current issues I have found, and I find it very useful when looking at other player's skins, or getting player heads for my website, Thanks!
