### ISSUE TITLE
Don't force SSL

### ISSUE THREAD

**Issue by njb-said** [minotar/imgd#164]
The main reason I am using another avatar site (not going to name names) over minotar is because of the fact it forces SSL connections. Is there a reason it does this?

**Comment by LukeHandle** [comment]
I assume it's because we want to encourage the use of SSL when using minotar. Few reasons for that would likely be along the lines of verifying that you are talking to minotar, and that there is a large opinion that people consider SSL to be better on than off.

If people still request the HTTP version then they can be MITM before the redirect, but they would be manually specifying HTTP.

What problems would it cause for you? The overhead of the extra SSL shouldn't cause any issues?

**Comment by njb-said** [comment]
I am seeing 100-400ms added to each request because of it, surely if people want SSL they will use it?

**Comment by jomo** [comment]
Interesting:

```shell
$ curl -w "@curlformat.txt" "http://minotar.net" -o /dev/null
    time_namelookup:  0.014
       time_connect:  0.038
    time_appconnect:  0.000
   time_pretransfer:  0.038
      time_redirect:  0.000
 time_starttransfer:  0.060
                    ----------
         time_total:  0.060

$ curl -w "@curlformat.txt" "https://minotar.net" -o /dev/null
    time_namelookup:  0.005
       time_connect:  0.025
    time_appconnect:  0.374
   time_pretransfer:  0.374
      time_redirect:  0.000
 time_starttransfer:  0.402
                    ----------
         time_total:  0.421
```

**Comment by clone1018** [comment]
Not forcing it sounds pretty logical, and it's easily possible.

**Comment by connor4312** [comment]
Is that a flaw in _having_ SSL, or just how we have it configured/set up on Minotar?

**Comment by LukeHandle** [comment]
Use of SSL does add some initial round trips but the SSL session is usually reused for subsequent connections. The set-up here is likely CloudFlare just forcing SSL.

**Comment by clone1018** [comment]
Both nginx and cf require it currently. We get double overhead because cf => nginx

**Comment by LukeHandle** [comment]
This should now be fixed. Just deployed some new infrastructure and fixed up some of these niggles. Both https://minotar.net/ and http://minotar.net/ are functional.

**Comment by clone1018** [comment]
Please ignore LukeH's use of the word niggles...

**Comment by MisterFixx** [comment]
lmao ^

**Comment by LukeHandle** [comment]
I'm tempted to redirect just the HTML homepage to SSL and leave all the imgd things on either.

**Comment by jomo** [comment]
I can confirm that works great, even with HSTS.
