### ISSUE TITLE
Cache??

### ISSUE THREAD

**Issue by WaterXCubic** [minotar/imgd#165]
I wanna ask that is there a cache on your website?My friend got a skin and when i use Minotar,it doesn't shows it,is there a solution?

**Comment by connor4312** [comment]
By default there's a 48 hour cache for Minotar skins.

**Comment by MisterFixx** [comment]
48 hours? dam.

**Comment by ApfelUser** [comment]
@WaterXCubic maybe close this issue now? If you want lesser caching-times you can self host imgd too.

**Comment by MisterFixx** [comment]
Yeah but why 48 hours? and what happens after 48 hours? does the cache automatically deletes or does it wait for the next request for that usernames and then deletes it?

**Comment by LukeHandle** [comment]
This will be lowered from 48 hours to a few. They expire and are removed from the cache after the time.

**Comment by LukeHandle** [comment]
This is currently now set to 2 hours. We'll see how this goes and adjust if required.

That's 2 hours cached at Redis, Varnish and CloudFlare, theoretically, you may see longer update times for numerous reasons.
