### ISSUE TITLE
Warning on build

### ISSUE THREAD

**Issue by ApfelUser** [minotar/imgd#166]
warning: code.google.com is shutting down; import path code.google.com/p/gcfg will stop working

**Comment by LukeHandle** [comment]
Good catch, I'll be putting some time into this the next 2 nights between working night shifts. Hopefully I can get the stuff I spent time on a few months back in a release state as well.

**Comment by LukeHandle** [comment]
Fixed in d5d3ac05e78a2c78e5dc3a5679754db7543c0594
