### ISSUE TITLE
Proper CORS support

### ISSUE THREAD

**Issue by Paril** [minotar/imgd#167]
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes

Image tags have a "crossOrigin" attribute which can be set to "anonymous", which sends the Origin of "null" to the web server; if the web server responds with "Access-Control-Allow-Origin: null", it is allowed to use the content per CORS rules (and is anonimized - the web server doesn't get any cookies or data from the origin, which makes this safe for clients not to expose unnecessary data to the web server. This is preferred over the "Access-Control-Allow-Origin: *" method).

It'd be nice if Minotar followed this so that we @ PlanetMinecraft can use Minotar requests in WebGL or other currently-disallowed client-side processing.

**Comment by connor4312** [comment]
We don't really want to request Origin to be null... the [w3 cors spec](http://www.w3.org/TR/cors/#security) says that

> A resource that is publicly accessible, with no access control checks, can always safely return an Access-Control-Allow-Origin header whose value is "*".

which is the pretty much the globally standard way of doing things as far as I have seen or head.

**Comment by Paril** [comment]
Yep you're right, sorry, I thought both were null but only Origin is null, the response header value is still '*'.

**Comment by LukeHandle** [comment]
This is now rolling out live.
