### ISSUE TITLE
Add helm layer to busts/full body

### ISSUE THREAD

**Issue by Phoenix616** [minotar/imgd#169]
Feature Request to either add helm layers to busts/full body or provide separate endpoints for these options.

Maybe there should even be a more dynamic way because the full body can now have a helm layer. (Or just default to pasting it over the skin, which probably would make this a lot easier)

**Comment by LukeHandle** [comment]
Hey there,

I believe we currently already have this at https://minotar.net/armour/body/Phoenix616 and https://minotar.net/armour/bust/Phoenix616 ? They are full armour (/armor) layers applied over the normal.

Un-documented, so the blame is on us :laughing: but is that what you were after?

**Comment by Phoenix616** [comment]
Yes, that was exactly what I was after. Should've looked into the code and not just into the documentation. :sweat_smile: 

Thanks for the info!
