### ISSUE TITLE
SSL Certificate expired

### ISSUE THREAD

**Issue by niklaswa** [minotar/imgd#171]
The SSL Certificate of minotar.net is expired

**Comment by clone1018** [comment]
cc @LukeHandle

**Comment by clone1018** [comment]
Common Name (CN)	sni72138.cloudflaressl.com
Organization (O)	<Not Part Of Certificate>
Organizational Unit (OU)	Domain Control Validated
Serial Number	42:59:95:50:A6:D4:B3:B7:7C:3E:25:E7:59:D4:DE:7A
Issued By

Common Name (CN)	COMODO ECC Domain Validation Secure Server CA 2
Organization (O)	COMODO CA Limited
Organizational Unit (OU)	<Not Part Of Certificate>
Validity Period

Issued On	Friday, April 3, 2015 at 7:00:00 PM
Expires On	Tuesday, October 20, 2015 at 6:59:59 PM

**Comment by clone1018** [comment]
Does that mean this is on CloudFlare's end?

**Comment by LukeHandle** [comment]
What on earth..? I wonder if there is some setting which has confused CF in their panel.

**Comment by clone1018** [comment]
I've opened a ticket with CloudFlare.

**Comment by clone1018** [comment]
"""Your request (#621342) has been submitted and a Technical Support Engineer will be contacting you shortly. Priority is given to Enterprise, Business and Pro customers, in that order."""

**Comment by clone1018** [comment]
> Thanks for getting in touch and reporting this issue. We're currently investigating this and will respond when this is resolved for you.

**Comment by clone1018** [comment]
> This issue should now be resolved entirely for you - thanks for your patience while we worked on this for you.

> Should you see any other issues, please do get in touch and provide a screenshot of any issue you see as well as details of your browser via https://aboutmybrowser.com

> I will mark this as solved but do let us know if you have any further questions or issues.

**Comment by LukeHandle** [comment]
From 16:40 GMT my 4 location monitoring picked this up as being fixed. Slightly surpised this ended up happening though :-1:

**Comment by clone1018** [comment]
Thankfully we have another year until it potentially happens again 

Expires On	Thursday, October 20, 2016 at 6:59:59 PM

**Comment by connor4312** [comment]
_marks it on the calendar_

**Comment by MisterFixx** [comment]
and when will happen when it expires?

**Comment by ApfelUser** [comment]
CF certificates usually shouldn't expire, or actually automatically be updated by CF. So in general this should not happen again, my guess is that it was just a hiccup on CF's side.
