### ISSUE TITLE
Issue with skin?

### ISSUE THREAD

**Issue by clone1018** [minotar/imgd#172]
> My skin doesn't work on Minotar - IGN is Phineas; other people's skins
work though, it's definitely just me & the skin servers aren't down.
This is really annoying for forums for servers like Hypixel and other
websites.

Got this in an email, haven't looked into it yet.

**Comment by LukeHandle** [comment]
Can't replicate, looks (assumed) fine for me.

https://minotar.net/armour/body/Phineas

![phineas](https://cloud.githubusercontent.com/assets/799079/10706831/af94de1c-79e2-11e5-9db4-6c4d4c35f88f.png)

**Comment by ThePhineas** [comment]
Hmm, didn't work yesterday.

**Comment by clone1018** [comment]
@ThePhineas What was shown? An error? A steve skin? A different skin?

**Comment by ThePhineas** [comment]
@clone1018 A Steve skin.

**Comment by LukeHandle** [comment]
Hey,

I'll close this off, but please let us know in the future if there are issues and ideally supply the headers that you get when requesting the image (look in your browsers "Developer Tools").

If you saw a Steve skin it is likely there was a an internal error or the endpoints where not accepting our requests at the time.
