### ISSUE TITLE
Does cache ever reset?

### ISSUE THREAD

**Issue by imRobust** [minotar/imgd#173]
Hey,

I have an avatar from an account that has changed its username ages ago, Minotar still returns an avatar for the old username (which is not used by an account atm) and for my new username it returns the old avatar. I've had this username quite a while now.

Do you ever reset the cache? If so, how long is it cached for? Can I force a cache refresh?

Cheers.

**Comment by clone1018** [comment]
I think these are our current values:

> This is currently now set to 2 hours. We'll see how this goes and adjust if required.
That's 2 hours cached at Redis, Varnish and CloudFlare, theoretically, you may see longer update times for numerous reasons.

@imRobust It'll be helpful to know your ingame username to figure out what's happening and why you're avatar is being cached longer.

**Comment by LukeHandle** [comment]
Hey there,

If the system is healthy, a skin will be cached at the backend for 2 hours and also cached at CloudFlare for the same amount of time. With a perfect storm, CloudFlare may make a request which is about to expire on the backend but hasn't and then cached it for 2 hours, in this case, it could end up up to ~4 hours old.

If we are talking about a skin which was changed days/weeks/months ago, potentially, Minotar is unhealthy is returning a skin from the old S3 infrastructure.

I'll close this off, but please let us know in the future if there are issues and ideally supply the headers that you get when requesting the image (look in your browsers "Developer Tools").
