### ISSUE TITLE
Update copyright

### ISSUE THREAD

**Issue by MisterFixx** [minotar/imgd#175]
I'm not sure that this is worth opening a whole issue for, but the copyright on the main page of minotar.net says "Copyright 2014 – Axxim, LLC"

**Comment by LukeHandle** [comment]
This was updated to 2016 previously in https://github.com/minotar/minotar.net/commit/be0dc23c829953301f962c0e39fd3c9f183040cb

It needs a further update and patch to 2017 - either way, not for here or too major.
