### ISSUE TITLE
Problem with Installing.

### ISSUE THREAD

**Issue by OfficialCRUGG** [minotar/imgd#185]
Hello.

I'm stuck at theese two commands of the installation:
`$ export GOPATH=pwd`
`$ go get`

When doing `go get` it just says: _"go install: no install location for directory /home/imgd outside GOPATH"_

**Comment by LukeHandle** [comment]
Hey there @OfficialCRUGG, thanks for reaching out!

I've pushed/tagged a new release here which thanks to new pipeline, includes a Linux and Mac build for x86_64:

https://github.com/minotar/imgd/releases/tag/2.10.0

If you want to install from source, instead visit here:

https://golang.org/doc/install#install

Then perform a `go get -u github.com/minotar/imgd`. a `go build` and `./imgd` will get you up and running. Rename the example config to `config.gcfg` and update as needed. "Memory" should be acceptable but is not tested at a particularly large scale. Minotar uses Redis.

If you are serving more than 500 or so unique skins per 10 minutes, you will see issues with rate-limiting. Also, we are a little more stable than the past few days, so by all means see how today goes with us as well.
