### ISSUE TITLE
Steve Skin Appears

### ISSUE THREAD

**Issue by KipperedSnack** [minotar/imgd#188]
Seem to be getting this lately:
![image](https://user-images.githubusercontent.com/20378331/36645999-22a68eae-1a37-11e8-9beb-9c5c71bd46cd.png)

**Comment by MisterFixx** [comment]
This is a known issue since Mojang has [shut down the legacy skin servers](https://bugs.mojang.com/browse/WEB-985).

**Comment by LukeHandle** [comment]
Hey there. This was tracked over in #181. I had initially closed it unintentionally via a PR, but will re-open it pending the planned full resolution.

Minotar as a whole is _mostly_ mitigated now (<4% of lookups on our backend requests are rate-limited). Certain traffic spikes push us into the red zone though which has a planned resolution.
