### ISSUE TITLE
signals.go Undefined!

### ISSUE THREAD

**Issue by Taiizor** [minotar/imgd#193]
.\signals.go:31:7: undefined: syscall.SIGUSR1
.\signals.go:50:7: undefined: syscall.SIGUSR2
.\signals.go:80:33: undefined: syscall.SIGUSR1
.\signals.go:80:50: undefined: syscall.SIGUSR2

**Comment by LukeHandle** [comment]
Hi there @Taiizor. Are you on Windows? Are you able to try the `develop` branch and use Docker/the Dockerfile and see if that works?

**Comment by Taiizor** [comment]
> Hi there @Taiizor. Are you on Windows? Are you able to try the `develop` branch and use Docker/the Dockerfile and see if that works?

I am using the Windows platform.

**Comment by LukeHandle** [comment]
@Taiizor awesome. Give the _Docker for Windows_ a go. It uses Hyper V behind the scenes and should work 👍

**Comment by M1XT3NZ** [comment]
may be kinda late, but i have the same problem and i already tried the docker
