### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by ChukiStrike** [minotar/imgd#196]
The page doesn't work, does it? Always return Steve.
Are they going to fix it or did they leave it behind?

**Comment by LukeHandle** [comment]
Hey @ChukiStrike, did you have an example of a page that's not working for you? Had a quick browse and test of a couple of users and seems okay?

**Comment by jomo** [comment]
Mojang started rate limiting their API. I guess minotar is also affected by this? See https://github.com/crafatar/crafatar/issues/260

**Comment by ChukiStrike** [comment]
@LukeHandle 
![werwerwerwr](https://user-images.githubusercontent.com/38164175/77263673-2680e900-6c99-11ea-92a6-4b6000af3d3e.jpg)

**Comment by Arc4d3** [comment]
I also have the problem. On Crafatar there is no problem. Is there any workaround ?

**Comment by OpenSauce04** [comment]
I have this problem as well with certain skins but not others. Please fix this!

**Comment by GiovanH** [comment]
Seems like it's still just down.

**Comment by PersonalDom** [comment]
Still down..

**Comment by MisterFixx** [comment]
https://shx.gg/dWUUca.png
Looks quite fine here

**Comment by clone1018** [comment]
Hey folks, please open a new ticket with some more info if Minotar is down for you! Be sure to include a comment of what exactly you are experiencing, and any screenshots you can take of the problem.
