### ISSUE TITLE
Overlay not displayed correctly

### ISSUE THREAD

**Issue by Yasu-San** [minotar/imgd#198]
I have the problem that the Overlays of some Accounts are not displayed correctly.

<details>
<summary><code>https://minotar.net/armor/body/Alphawolf_Yasu</code> gives me this skin:</summary>
<img title="Alphawolf_Yasu-Minotar" src="https://user-images.githubusercontent.com/19592790/83324168-a14f1d00-a263-11ea-9a08-fb9b8c2710d2.png">
</details>

<details>
<summary>While NameMC gives me this one:</summary>
<img title="Alphawolf_Yasu-NameMC" src="https://user-images.githubusercontent.com/19592790/83324197-d3607f00-a263-11ea-9c46-81a43f5d9375.png">
</details>

The last one is the way Minecraft is rendering the skin.

**Comment by LukeHandle** [comment]
Hi, this issue should now be fixed from the work in https://github.com/minotar/imgd/pull/214
