### ISSUE TITLE
Skin shows as default Steve skin

### ISSUE THREAD

**Issue by RCNOverwatcher** [minotar/imgd#200]
When using my UUID and typing in the [web link](https://minotar.net/helm/d70332578cef43d99529b96789e27a25) my helm + avatar shows as the default skin. I have tried experimenting with different extensions (.png, .jpg, etc) but to no avail. Any help would be appreciated. 

(Normal skin screenshot attached)
![image](https://user-images.githubusercontent.com/49075095/99887207-46a6e480-2c3a-11eb-9acd-ef285651648d.png)

**Comment by RCNOverwatcher** [comment]
Note that other people on my server using the same webhook and their avatars work perfectly.

**Comment by LukeHandle** [comment]
Hi @RCNOverwatcher , there was another report over in #201, so you aren't alone. It's likely that we hit a rate limit. The skin is currently loading fine for me, so hopefully just a blip.

Using the UUID as you as is the best route, so I can't suggest anything more. Changing the extension won't normally help - it's likely an issue on our endpoint unfortunately.
