### ISSUE TITLE
Doing a pull request from the api gives me a steve skin, not the skin I expected

### ISSUE THREAD

**Issue by narwhql** [minotar/imgd#201]
When trying to do a pull request from 'https://minotar.net/helm/1GamingHard_', the only thing I see is a steve head.

My minecraft username: 1GamingHard_

Please fix this issue, it is really annoying or tell me if I am doing anything wrong.

Thanks!

Edit: Using other usernames works and their skins show perfectly fine, it seems like only my username is not working.

**Comment by LukeHandle** [comment]
Hi @narwhql, I can see someone else had a similar issue (#200), so it's not just you, more likely a blip where we hit the rate limits for requests.

I'd recommend using the UUID endpoint instead as this is more resilient to the rate limits:

https://minotar.net/helm/89633446a89243b5a544ff39086a6497

(it's worth making that recommendation to the owner of your integration if needs be)
