### ISSUE TITLE
Skin loading doesnt work

### ISSUE THREAD

**Issue by HenyPotter** [minotar/imgd#203]
![image](https://user-images.githubusercontent.com/60482905/109463773-e0660500-7a65-11eb-8d53-9d192b213ae9.png)

**Comment by LukeHandle** [comment]
Seems we hit some kernel bug. 

Something gets stuck in a syscall loop and runs at 100% on 1 CPU:
![Screenshot 2021-03-01 at 17 23 35](https://user-images.githubusercontent.com/799079/109534139-e930f800-7ab2-11eb-92bf-063a4b5ffd75.png)

(logging in, no process shows _any_ CPU usage more than a percent or so, so very freaky)

We also see at this point, we get a memory leak where our (un+)reclaimable memory both start heading up.

![Screenshot 2021-03-01 at 17 19 28](https://user-images.githubusercontent.com/799079/109533658-5ee89400-7ab2-11eb-828a-b80ac432090f.png)

![Screenshot 2021-03-01 at 17 14 49](https://user-images.githubusercontent.com/799079/109533655-5db76700-7ab2-11eb-9845-7590593fcf09.png)




```
Feb 27 06:46:22 redis1 update-apt-xapi[8418]: segfault at 24 ip 000000000052a36c sp 00007fff26997860 error 6 in python2.7[400000+2bc000]
Feb 27 06:46:22 redis1 BUG: unable to handle kernel paging request at fffffff47824f0a0
Feb 27 06:46:22 redis1 IP: [<ffffffffa007c59f>] drm_mm_insert_node_in_range_generic+0x1af/0x340 [drm]
Feb 27 06:46:22 redis1 PGD 1c11067 PUD 0
Feb 27 06:46:22 redis1 Oops: 0000 [#2] SMP
```

It appears syslog was killed around this point (probably an OOM). First the Username -> UUID cache died, but the crash on the session data was more impactful.

We got some assistance with the ratelimits so things should return to normal "soon".

**Comment by HenyPotter** [comment]
Okay, thank you and have a nice day! :)

**Comment by KuCZik** [comment]
Still does not work on some UUIDs or names, Notch is working but KuCZik not

**Comment by harvanchik** [comment]
Still seems to be a problem.  Getting Steve heads for valid uuids.

https://minotar.net/helm/6f23cfa0b8e34c35855bdfb94b4f8e91/100.png

https://namemc.com/profile/JellySand.2

**Comment by harvanchik** [comment]
This should be reopened.

**Comment by LukeHandle** [comment]
Hi @harvanchik , I've been checking this off and on the last few days and I haven't seen an issue loading the helm. Are you able to screenshot the error you are seeing?
