### ISSUE TITLE
Domain renewal required

### ISSUE THREAD

**Issue by LukeHandle** [minotar/imgd#205]
Looks like we're parked. Pending @clone1018. I've poked him, he's normally around now-ish.

**Comment by AcaiBerii** [comment]
Looks like the site is still offline, any other way we could get avatars still?

**Comment by clone1018** [comment]
We fixed it over 48 hours ago, what exactly is offline? What message are you getting? 

More info: https://github.com/minotar/minotar.net/issues/18#issuecomment-816643432

**Comment by LukeHandle** [comment]
Hi @AcaiBerii

This issue is "fixed" - at least, to the level of DNS/NS propagation delays still possibly causing issues.

Are you still seeing the Namecheap parked page? The point of domain expiry, the nameservers (NS) for the domain would have been changed, and then changed back at the point of renewal. This can take "up to 48 hours", though many see it in a few hours (as did I). I've just updated https://github.com/minotar/minotar.net/issues/18, where clone reported he renewed the domain - it is now 48 hours since then.

The delay comes from different DNS resolvers caching the information for varying times. If you use a local ISP DNS server, you might see the old value for longer than if you used a public resolver like Cloudflare (1.1.1.1), Google (8.8.8.8), Quad9 (9.9.9.9), OpenDNS etc. Checking using a "global checker", it reported fairly quickly the correct addresses: https://www.whatsmydns.net/#A/minotar.net

On your local computer, you could try an `nslookup` (Windows) or `dig` (Linux) to verify the addresses being resolved.

```
>nslookup minotar.net
[...]
Non-authoritative answer:
Name:    minotar.net
Addresses:  2606:4700:3038::6815:ea47
          2606:4700:3038::6815:ea46
          104.21.234.70
          104.21.234.71
```

```
$ dig +short minotar.net                                                                                                                                                       ─╯
104.21.234.71
104.21.234.70
```

**Comment by AcaiBerii** [comment]
I guess today I temporarily couldn't view the website. No problem now, everything works. Thanks.
