### ISSUE TITLE
Server not working (503 Service Temporarily Unavailable)

### ISSUE THREAD

**Issue by viminio** [minotar/imgd#211]
![image](https://user-images.githubusercontent.com/62722905/146394287-62471402-0fe9-47c3-afe0-41aaae3e3461.png)

**Comment by Chew** [comment]
Little bit disappointing :(

I spun up https://minotar.chew.pro for now, just do the normal `/avatar/name.png`

**Comment by LukeHandle** [comment]
Hey, sorry about these issues. Started a new job and haven't been able to put the required time in here.

One of the limitations we've previously had was memory usage in Redis. We had to shift the platform around over the summer as the infra was aged. It was not viable to run multiple Redis instances with high memory requirements so I've been exploring moving towards a SSD backed store as a route to reduce the memory usage. Unfortunately, this has been a mixed path where we're able to hold more data and serve results very fast - but the now larger cache size has become less manageable and can see less predictable memory usage. There's tuning needed here and I have some more ideas to improve stability.

As a firefighting route, I've just now shifted from Varnish to nginx for the frontend caching and I'm hopeful that this will leave more breathing room with the memory. Things are a bit more stable now, and I'll have a little time over the next week to improve things further,

**Comment by Chew** [comment]
Thanks for the response!

I do recommend tuning your Cloudflare settings a bit:
- Under SSL/TLS > Edge Certificates, enable:
  - Always Use HTTPS
  - Automatic HTTPS Rewrites
- Caching > Tiered Caching, enable "Argo Tiered Caching"

I also added this page rule:
![image](https://user-images.githubusercontent.com/8278263/147197237-60a85f84-fa05-4168-9a5b-0d6c5a684f50.png)

It essentially cached everything on Cloudflare's end for a month. This may be a bit too strict for your liking, but it essentially ensures it serves from Cloudflare long before it ever hits you. Pro shows you what's hitting and not, but it is $20/mo, which might be worth it if you don't already have it, has some very useful analytics 😄
