### ISSUE TITLE
Question: Does minotar.net collect any personal data?

### ISSUE THREAD

**Issue by Reception123** [minotar/imgd#212]
We would like to use content from your website on our site but in order to comply with the GDPR we would like to know if any PII is collected from your website.

**Comment by Reception123** [comment]
Hi, we are a wiki farm (Miraheze) and one of our wikis which is a Minecraft-related wiki uses your website currently (wiki.mineland.eu). So we can comply with the GDPR we've implemented a new policy for external sites which is where the question comes from.

Is IPs the only thing that is logged?

**Comment by LukeHandle** [comment]
I've just checked - we do not log user IPs, we only log the source IP, which will always be Cloudflare for us. We do not log the `X-Forwarded-For` or `CF-Connecting-IP` headers. 

We do log the User Agent, Request URI, Referrer, (though none are PII - especially without a users real IP). They are kept purely for debug / error logging and cleared after a few days. We don't sell any of this data.

For our homepage, we recently switched to [Plausible](https://plausible.io/) for analytics as this is more privacy focused (no cookies and EU based), so no Google cookie tracking there.

If we ever implement any sort of analysis of our requests, we will never store the full IP (just the first 3 octets which would be for understanding source country and reactive in case of malicious requests with a /24 block).

I think this answers the query here - please re-open if you have any further questions, thanks!

**Comment by Reception123** [comment]
Thanks a lot for the information!
