### ISSUE TITLE
Reopen #198

### ISSUE THREAD

**Issue by 1fxe** [minotar/imgd#217]
The transparency seems to be working fine.

The issue he reported is due to the leg textures being swapped on the legs for some reason (arms and torso are fine). I can take a look at it this weekend 👍#198

https://minotar.net/armor/body/4ddcd747679e4fc193fd04904e0a0260/100.png

![body (1).png](https://user-images.githubusercontent.com/37674069/167972925-1d14cfb7-8f0b-4e56-a517-8ed1cd0e912d.png)

https://github.com/minotar/imgd/blob/f51c98c9dc1ae19069cfe5c9b0be778b299cc054/process.go#L256

**Comment by LukeHandle** [comment]
Fixed per https://minotar.net/armor/body/4ddcd747679e4fc193fd04904e0a0260/200

![200](https://user-images.githubusercontent.com/799079/168187859-ca7beae1-6e99-43a2-8dc0-c2f146cead9f.png)

Thanks!
