### ISSUE TITLE
Outage? Connection timed out 

### ISSUE THREAD

**Issue by zanethefox** [minotar/imgd#229]
Hi there! For the last days I have noticed that Minotar images/avatars do not load anymore and are also not showing the usual Steve fallback image either. The avatar URL returns error code 522: Connection timed out. 

Would it be possible to please investigate this outage?

Thanks a lot! :)

**Comment by chelminski** [comment]
#escalation

**Comment by LukeHandle** [comment]
I've just logged into things to check what's up, and it decided to load for me? I did see a 522 a short whole ago though.
![image](https://github.com/minotar/imgd/assets/799079/ba073623-2fe4-4cb1-9a83-efa7fdecaaa4)

Is this intermittent, or just fixed itself?

_edit: Still problematic I think. Looks like some DigitalOcean upgrade occurred and things fell apart_

**Comment by zanethefox** [comment]
I am not entirely sure, unfortuately it's still loading most skins with error code 522. The homepage is showing up like this for me:
<img width="1146" alt="image" src="https://github.com/minotar/imgd/assets/62026364/2f67762c-0fc3-4f99-9c40-472287e4795e">

And the error message on images:
<img width="1413" alt="image" src="https://github.com/minotar/imgd/assets/62026364/f85433fc-76b6-4d6f-9740-0fb199770a74">

**Comment by chelminski** [comment]
Yes, because it (homepage) is in the cloudflare cache, but the server is not responding. (Probably - I think so.)

**Comment by LukeHandle** [comment]
Okay, should be fixed. Fire is out.

> edit: Still problematic I think. Looks like some DigitalOcean upgrade occurred and things fell apart

Normally these automatic upgrades occur without issue (and, I've not had to touch things with K8 for quite a while :D). Part of the upgrade process involves it adding new servers to the pool, and removing old servers.

We use "floating IPs" that are added/removed from the nodes based on their availability. These should have been added to the new nodes as they spun up, but it appears something has broken that process.

I added the IPs manually to the nodes, and the issue resolved... but it'll come back when they next have a maintenance occur. Will need some further investigation.

**Comment by zanethefox** [comment]
Thanks so much for your quick response :D I really do appreciate it lots.

Hopefully the automatic process can be fixed easily, but I am glad that things are loading quickly for now again!

**Comment by LukeHandle** [comment]
Issue tracked back to an update to the image that does this bit:
> We use "floating IPs" that are added/removed from the nodes based on their availability. These should have been added to the new nodes as they spun up, but it appears something has broken that process.

[That update](https://github.com/digitalocean/flipop/commit/c7dd6cafd6fdf48d2143ff6ba15e373880f71943#diff-41da5c14cb085c2991c54efc50fb98dfa6d6d8453ab4c536488acb5f565a1e43R71) was due to an upstream API change that [removed an old way of doing things and replaced it with a new way](https://github.com/kubernetes/client-go/commit/27bbe765353fa01ed516b11bde1da82ae6f6c3bc). The new way required a different K8 resource and we hadn't granted the service access to manage the new resource / type.

Should be all fixed now!
